### PR TITLE
Began to work on switch "Block Ads"

### PR DESCRIPTION
**Pull request by saagarjha**
Still buggy, cannot guarantee it works

### CODE REVIEW

**Comment by jusleg** [comment]
Keep up the good work

**Comment by saagarjha** [comment]
Should I merge this?

**Comment by jusleg** [comment]
Do the filter work? It's your call. I do not have access to my mac. Will the app still work if you merge now?

**Comment by saagarjha** [comment]
I cannot guarantee it…let's wait until I test it more

**Pull request closed without merging**
