### PR TITLE
Fixed the App Icon assets

### PR DESCRIPTION
**Pull request by saagarjha**

### CODE REVIEW

**Comment by jusleg** [comment]
I have a conflict what should I do to merge this correctly

**Comment by saagarjha** [comment]
What are the conflicts?

**Comment by jusleg** [comment]
I  dont know github just wont let me merge. I am really new to git and do not really understand all of this

**Comment by jusleg** [comment]
I could manually merge it . I will try this

**Comment by saagarjha** [comment]
Can you give me write access?

**Comment by jusleg** [comment]
sure

**Pull request closed without merging**
